services:
  app:
    image: ghcr.io/amogusau-cell/yt-down:latest # Use versions such as 0.0.0 for specific version.
    container_name: yt-down
    restart: unless-stopped
    ports:
      - "8080:80" # host:container change 8080 to whatever port you want
    environment:
      - JWT_SECRET=notsosecretdefaulttokenthatyoushouldprobablychangeprettysoon # Change this to a random string for security purposes.
    volumes:
      - ./cache:/app/backend/cache
      - ./config:/app/backend/config
      - ./Shows:/app/backend/Shows
      - ./Videos:/app/backend/Videos
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s